name: demands_scraper

on:
  push:
    push:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests bs4 python-dateutil slack-sdk slackclient
      
      - name: run scraper
        env:
          slack_api_token: ${{ secrets.SLACK_API_TOKEN }}
          repo-token: ${{secrets.REPO_TOEN}}
        run: python scrapers/poweroutages.py

      - name: "Commit and push if it changed"
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push